language: python
python:
  - "2.7"
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev
# command to install dependencies
install:
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install -r requirements.txt"
before_script: python2.7 setup.py develop
# command to run tests
script: python2.7 -m unittest discover -b
